version: '3.8'
services:
  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_DATABASE=kaddemdb
    ports:
      - "3307:3306"
    secrets:
      - mysql_root_password
    volumes:
      - db:/var/lib/mysql

  backend:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    ports:
      - "8090:8089"
    stdin_open: true
    tty: true
    volumes:
      - .m2:/root/.m2

secrets:
  mysql_root_password:
    external: true
    name: mysql_root_password

volumes:
  db:
