version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root  # Change this to your desired password
      - MYSQL_DATABASE=kaddemdb
    ports:
      - "3307:3306"
    # Remove the 'secrets' section
    volumes:
      - db:/var/lib/mysql

  backend:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    ports:
      - "8090:8089"
    stdin_open: true
    tty: true
    volumes:
      - .m2:/root/.m2

volumes:
  db:
